name: Appium CI

on:
  push:
    branches: [ "ci" ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
          api-level: [30]
          target: [default]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci

    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v2 # install and create the Emulator
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: npm start # running our test with info to check the results

    - name: Upload allure-results as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: allure-results
        path: allure-results

  reporting:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download allure-results artifacts
        uses: actions/download-artifact@v3
        with:
          name: allure-results
          path: allure-results

      - name: Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-report
