name: Appium CI

on:
  push:
    branches: [ "ci" ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
          api-level: [30]
          target: [default]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v1 # install and create the Emulator
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: npm start # running our test with info to check the results
